openapi: 3.0.0
info:
  title: Election API Service
  version: 1.0.0
paths:
  /result/{id}:
    get:
      summary: Get a candidate by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
  /scoreboard: 
    get:
      summary: Get the scoreboard for the election
      responses:
        '200':
          description: Successful response

